-- psql --host=localhost --username=postgres -q --file=DDL_ELEICAO.txt

DROP SCHEMA ELEICAO_2024 cascade;
CREATE SCHEMA ELEICAO_2024;
SET SEARCH_PATH TO ELEICAO_2024;
SET datestyle TO DMY;
\encoding 'UTF8'

CREATE TABLE CARGO (
  CD_CARGO INTEGER PRIMARY KEY,
  DS_CARGO TEXT
);

CREATE TABLE PARTIDO (
  NR_PARTIDO INTEGER PRIMARY KEY,
  SG_PARTIDO TEXT,
  NM_PARTIDO TEXT
);

CREATE TABLE FEDERACAO (
  NR_FEDERACAO INTEGER PRIMARY KEY,
  NM_FEDERACAO TEXT,
  SG_FEDERACAO TEXT
);

CREATE TABLE GENERO (
  CD_GENERO INTEGER PRIMARY KEY,
  DS_GENERO TEXT
);

CREATE TABLE GRAU_INSTRUCAO (
  CD_GRAU_INSTRUCAO INTEGER PRIMARY KEY,
  DS_GRAU_INSTRUCAO TEXT
);

CREATE TABLE ESTADO_CIVIL (
  CD_ESTADO_CIVIL INTEGER PRIMARY KEY,
  DS_ESTADO_CIVIL TEXT
);

CREATE TABLE COR_RACA (
  CD_COR_RACA INTEGER PRIMARY KEY,
  DS_COR_RACA TEXT
);

CREATE TABLE OCUPACAO (
  CD_OCUPACAO INTEGER PRIMARY KEY,
 DS_OCUPACAO TEXT
);

CREATE TABLE COLIGACAO (
  SQ_COLIGACAO NUMERIC(12) PRIMARY KEY,
  NM_COLIGACAO TEXT,
  DS_COLIGACAO TEXT
);

CREATE TABLE CANDIDATO (
  SG_UF TEXT,
  NM_UE TEXT,
  CD_CARGO INTEGER REFERENCES CARGO(CD_CARGO),
  SQ_CANDIDATO NUMERIC(12) PRIMARY KEY,
  NR_CANDIDATO INTEGER,
  NM_CANDIDATO TEXT,
  NM_URNA_CANDIDATO TEXT,
  NM_SOCIAL_CANDIDATO TEXT,
  TP_AGREMIACAO TEXT,
  NR_PARTIDO INTEGER REFERENCES PARTIDO(NR_PARTIDO),
  NR_FEDERACAO INTEGER REFERENCES FEDERACAO(NR_FEDERACAO),
  SQ_COLIGACAO NUMERIC(12) REFERENCES COLIGACAO(SQ_COLIGACAO),
  SG_UF_NASCIMENTO TEXT,
  DT_NASCIMENTO DATE,
  CD_GENERO INTEGER REFERENCES GENERO(CD_GENERO),
  CD_GRAU_INSTRUCAO INTEGER REFERENCES GRAU_INSTRUCAO(CD_GRAU_INSTRUCAO),
  CD_ESTADO_CIVIL INTEGER REFERENCES ESTADO_CIVIL(CD_ESTADO_CIVIL),
  CD_COR_RACA INTEGER REFERENCES COR_RACA(CD_COR_RACA),
  CD_OCUPACAO INTEGER REFERENCES OCUPACAO(CD_OCUPACAO)
);

CREATE TABLE BEM_CANDIDATO (
  SQ_CANDIDATO NUMERIC(12) REFERENCES CANDIDATO(SQ_CANDIDATO),
  NR_ORDEM_BEM_CANDIDATO INTEGER,
  CD_TIPO_BEM_CANDIDATO INTEGER,
  DS_TIPO_BEM_CANDIDATO TEXT,
  VR_BEM_CANDIDATO NUMERIC(15,2),
  PRIMARY KEY(SQ_CANDIDATO, NR_ORDEM_BEM_CANDIDATO)
);


